// Giant series of flavor texts to spice up bot CX.
export default {
    UnknownCommand: {
        strings: (author: string, cmdname: string) => [
            `I'm sorry, ${author}. I'm afraid I can't do that.`,
            `Get a load of this guy, trying to use \`${cmdname}\` as a command.`,
            `I'm sorry, I don't know the command \`${cmdname}\`. Why don't you ask for help?`,
            `\`${cmdname}\`? Is this some sick kind of joke?`,
            `What are you even saying`,
            `I don't recognize \`${cmdname}\`. Maybe try something else?`,
            `Command \`${cmdname}\` not found. Please check your spelling.`,
            `Oops! \`${cmdname}\` isn't a valid command.`,
            `Looks like \`${cmdname}\` isn't something I can do.`,
            `Sorry, but \`${cmdname}\` doesn't seem to be a command I know.`,
            `Hmm, \`${cmdname}\` doesn't ring a bell.`,
            `Your free trial of WinRAR has expired. Please purchase a license to continue using \`${cmdname}\`.`,
            `\`${cmdname}\` ain't no command I ever heard of. They speak English in \`${cmdname}\`?`,
            `\`${cmdname}\`? I hardly knew her!`,
        ],
        emoji: [
            "🤖",
            "🤔",
            "🤨",
            "😒",
            "a:joey:768835939493478400",
            "a:deadass:1007451877476159578",
            "a:deepthought:747542528135266345",
            "a:asianoof:747545253896257585",
            "a:bruhv:740278121718218906",
            "a:cat:755949336877072425",
            "a:coolstorybro:1010958995986587678",
            "a:zamn:1010963288273723455",
            "a:thefuq:741823376867197009",
        ],
    },
    HelpCommand: {
        titles: [
            "Some commands, and what they do",
            "Here's what I can do",
            "I'm here to help!",
            "Need a hand?",
            "The Bombers Secret Society of Justice forever!",
            "My functionality is vast",
        ],
        calltoactions: (author: string) => [
            `${author}, here's some tips...`,
            `${author}, here's some commands...`,
            `${author}, you asked for help?`,
            `${author}, you need some help?`,
            `${author}, let me do it for you`,
            `${author}, I'm here to help`,
            `${author}, shouldn't you know these commands already?`,
        ],
        commandspecific: [
            "Here's how you use",
            "Help for",
            "Here's a refresher on",
            "This is how you use",
            "Here's the syntax for",
        ],
    },
};
