name: Pull Request Integration Testing

on:
    pull_request:

jobs:
    build_and_lint:
        name: Build and lint
        runs-on: ubuntu-latest
        permissions:
            packages: read
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up Node.JS 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run formatter
              run: npm run format

            - name: Build TypeScript to JavaScript
              run: npm run build

            - name: Run linter
              run: npm run lint

            - name: Commit formatted changes, if any
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Format code with Prettier"
                  branch: ${{ github.head_ref }}

    test_gamma:
        name: Test in gamma environment
        runs-on: ubuntu-latest
        permissions:
            packages: read
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up Node.JS 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "npm"

            - name: Install dependencies
              run: npm install --production

            - name: Build TypeScript to JavaScript
              run: npm run build

            - name: Run gamma tests
              run: npm start
              env:
                  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
                  RUNTIME_ENV: gamma
